#### Balancing imbalanced dataset

dataset -> 900 yes and 100 no -> the model is gonna have bias towards 900 yes hence we balancce the data set 
using 

1. up sampling : increase data points of the min value
2. down sampling : increase the data points of the max value

In [4]:
import numpy as np
import pandas as pd


  # set the random seed for reproducibility
np.random.seed(123)
n_samples=1000
class_0_ratio=0.9
n_class_0=int(n_samples* class_0_ratio)
n_class_1= n_samples-n_class_0

In [5]:
n_class_0, n_class_1

(900, 100)

In [15]:
## creating a dataframe with imbalance data set 


class_0= pd.DataFrame({
    'feature_1': np.random.normal(loc=0,scale=1,size=n_class_0),
    'feature_2': np.random.normal(loc=0,scale=1,size=n_class_0),
    'target':[0]*n_class_0
})
class_1=pd.DataFrame({
    'feature_1': np.random.normal(loc=0,scale=1,size=n_class_1),
    'feature_2': np.random.normal(loc=0,scale=1,size=n_class_1),
    'target':[1]*n_class_1
})

In [16]:
df=pd.concat([class_0,class_1]).reset_index(drop=True)

In [17]:
df

     feature_1  feature_2  target
0    -0.471276   0.328462       0
1     1.084072   1.038230       0
2    -0.379223   1.147064       0
3    -0.362274   0.638254       0
4    -0.681071  -1.075766       0
..         ...        ...     ...
995   0.720690  -0.021511       1
996  -0.050922   1.709793       1
997   0.709784   1.324917       1
998  -0.182311  -0.450763       1
999   0.838910   0.240773       1

[1000 rows x 3 columns]

In [11]:
df.head()

   feature_1  feature_2  target
0  -1.085631   0.551302       0
1   0.997345   0.419589       0
2   0.282978   1.815652       0
3  -1.506295  -0.252750       0
4  -0.578600  -0.292004       0

In [18]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [20]:
## upsampling 
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [27]:
from sklearn.utils import resample
# extrapolates the minority 

df_upsampled=resample(df_minority,replace=True,n_samples=len(df_majority),random_state=42)
df_upsampled.shape

(900, 3)

In [30]:
df_upsampled.head()

     feature_1  feature_2  target
951   0.701255  -1.943519       1
992   0.322342   1.289170       1
914   0.500618  -0.661830       1
971  -0.077056   0.907951       1
960  -1.369782  -1.017595       1

In [38]:
df_up_sampled=pd.concat([df_majority,df_upsampled]).reset_index(drop=True)

In [39]:
df_upsampled.head()

     feature_1  feature_2  target
951   0.701255  -1.943519       1
992   0.322342   1.289170       1
914   0.500618  -0.661830       1
971  -0.077056   0.907951       1
960  -1.369782  -1.017595       1